project:
  type: website
  output-dir: docs

website:
  title: "DATAIDEA"
  favicon: assets/dataidea-logo.png
  bread-crumbs: false
  page-navigation: true
  repo-actions: [issue]
  back-to-top-navigation: true
  reader-mode: true
  site-url: "https://blog.dataidea.org/"
  description: "Learn Programming For Data Science"
  repo-branch: main
  repo-url: "https://github.com/dataidea/dataidea-blog"
  navbar:
    right:
      - text: Home
        href: "https://blog.dataidea.org/"
      - text: About
        menu:
          - text: About Us
            url: "https://dataidea.org/#about"
          - text: Privacy Policy
            url: "https://dataidea.org/privacy_policy.html"
          - text: Terms of Service
            url: "https://dataidea.org/terms_of_service.html"
      - text: Subjects
        menu:
          - text: Data Science
            url: "https://science.dataidea.org/"
          - text: Web Development
            url: "https://web.dataidea.org/"
      - text: Resources
        menu:
          - text: Forum
            url: "https://chat.whatsapp.com/GuCZRyJICgO3Y7MPvDQKhi"
          - text: French
            url: "https://french.dataidea.org"
          - text: Football
            url: "https://football.dataidea.org"
          - text: Movies
            url: "https://movies.dataidea.org"
      - text: Contact
        href: "https://www.dataidea.org/#contact"
      - icon: twitter
        href: https://twitter.com/dataideaorg
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-title: Table of Contents
